/**
 * Backend-local copy of shared constants.
 * SOURCE OF TRUTH is d:\hc101\shared\constants\index.ts
 * Keep in sync when adding new shared constants.
 */

export const API_VERSION = 'v1';
export const API_BASE_PATH = `/api/${API_VERSION}`;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  RATE_LIMITED: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PHONE_NUMBER: 'INVALID_PHONE_NUMBER',
  INVALID_LOCATION: 'INVALID_LOCATION',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  PATIENT_NOT_FOUND: 'PATIENT_NOT_FOUND',
  AMBULANCE_NOT_FOUND: 'AMBULANCE_NOT_FOUND',
  HOSPITAL_NOT_FOUND: 'HOSPITAL_NOT_FOUND',
  DOCTOR_NOT_FOUND: 'DOCTOR_NOT_FOUND',
  EMERGENCY_NOT_FOUND: 'EMERGENCY_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  AMBULANCE_NOT_AVAILABLE: 'AMBULANCE_NOT_AVAILABLE',
  DUPLICATE_EMERGENCY: 'DUPLICATE_EMERGENCY',
  BED_NOT_AVAILABLE: 'BED_NOT_AVAILABLE',
  DOCTOR_NOT_AVAILABLE: 'DOCTOR_NOT_AVAILABLE',
  AI_SERVICE_ERROR: 'AI_SERVICE_ERROR',
  MAPS_API_ERROR: 'MAPS_API_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const;

export const USER_TYPES = {
  PATIENT: 'PATIENT',
  DOCTOR: 'DOCTOR',
  AMBULANCE_DRIVER: 'AMBULANCE_DRIVER',
  HOSPITAL_ADMIN: 'HOSPITAL_ADMIN',
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
} as const;

export const EMERGENCY_STATUS = {
  INITIATED: 'INITIATED',
  DISPATCHED: 'DISPATCHED',
  IN_TRANSIT: 'IN_TRANSIT',
  HOSPITAL_NOTIFIED: 'HOSPITAL_NOTIFIED',
  ARRIVED: 'ARRIVED',
  ADMITTED: 'ADMITTED',
  IN_TREATMENT: 'IN_TREATMENT',
  DISCHARGED: 'DISCHARGED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export const EMERGENCY_PRIORITY = {
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
} as const;

export const AMBULANCE_STATUS = {
  AVAILABLE: 'AVAILABLE',
  IN_SERVICE: 'IN_SERVICE',
  MAINTENANCE: 'MAINTENANCE',
  OFF_DUTY: 'OFF_DUTY',
} as const;

export const BLOOD_GROUPS = ['O+', 'O-', 'A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'UNKNOWN'] as const;

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
  MIN_LIMIT: 1,
} as const;

export const TIME_CONSTANTS = {
  JWT_EXPIRY: 3600,
  JWT_REFRESH_EXPIRY: 604800,
  CACHE_TTL_SHORT: 300,
  CACHE_TTL_MEDIUM: 1800,
  CACHE_TTL_LONG: 3600,
  CACHE_TTL_DAY: 86400,
  RATE_LIMIT_WINDOW: 900000,
  RATE_LIMIT_MAX_REQUESTS: 100,
  RATE_LIMIT_MAX_CRITICAL: 10,
  API_TIMEOUT: 5000,
  AI_SERVICE_TIMEOUT: 10000,
  AMBULANCE_RESPONSE_SLA: 5,
  DOCTOR_ASSIGNMENT_SLA: 10,
  HOSPITAL_ADMISSION_SLA: 30,
} as const;

// ── Appointment Constants ──────────────────────────────────────────────────────
export const APPOINTMENT_STATUS = {
  SCHEDULED: 'SCHEDULED',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW',
} as const;

export const APPOINTMENT_TYPES = {
  IN_PERSON: 'IN_PERSON',
  VIDEO_CALL: 'VIDEO_CALL',
  PHONE: 'PHONE',
} as const;

export const APPOINTMENT_DURATION_MINUTES = 30;

// Doctor recommendation scoring weights (must sum to 1.0)
export const RECOMMENDATION_WEIGHTS = {
  RATING: 0.30,
  PROXIMITY: 0.25,
  SPEED: 0.20,
  AVAILABILITY: 0.15,
  FAMILIARITY: 0.10,
} as const;

export const VIDEO_CALL_EXPIRY_HOURS = 2;
export const QR_CODE_EXPIRY_HOURS = 24;
export const PATIENT_ANALYTICS_RANGE_MONTHS = 12;
